# Generated by Django 5.2.10 on 2026-01-17 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='货物名称')),
                ('model', models.CharField(max_length=100, verbose_name='进货型号')),
                ('purchase_date', models.DateField(verbose_name='进货日期')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('supplier_contact', models.CharField(max_length=20, verbose_name='供应商联系方式')),
                ('purchaser', models.CharField(max_length=100, verbose_name='进货人')),
                ('receiver', models.CharField(max_length=100, verbose_name='收货人')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(verbose_name='进货数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总价格')),
                ('warehouse', models.CharField(max_length=100, verbose_name='入库仓库')),
                ('status', models.CharField(choices=[('in_stock', '已入库'), ('pending', '待入库')], default='pending', max_length=20, verbose_name='入库状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '进货记录',
                'verbose_name_plural': '进货记录',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='货物名称')),
                ('model', models.CharField(max_length=100, verbose_name='出货型号')),
                ('ship_date', models.DateField(verbose_name='出货日期')),
                ('region', models.CharField(max_length=100, verbose_name='出货地区')),
                ('warehouse', models.CharField(max_length=100, verbose_name='出货仓库')),
                ('shipper', models.CharField(max_length=100, verbose_name='出货人')),
                ('receiver', models.CharField(max_length=100, verbose_name='收货人')),
                ('contact', models.CharField(max_length=20, verbose_name='联系方式')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(verbose_name='出货数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='出货总价')),
                ('status', models.CharField(choices=[('shipped', '已发货'), ('received', '已签收'), ('exception', '异常')], default='shipped', max_length=20, verbose_name='出货状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '出货记录',
                'verbose_name_plural': '出货记录',
                'ordering': ['-ship_date', '-created_at'],
            },
        ),
    ]
