# Generated by Django 5.2.10 on 2026-02-21 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_contact', models.CharField(max_length=20, verbose_name='客户联系方式')),
                ('customer_address', models.TextField(verbose_name='客户地址')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='订单总金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('paid', '已付款'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='物流单号')),
                ('carrier', models.CharField(max_length=100, verbose_name='物流公司')),
                ('status', models.CharField(max_length=50, verbose_name='物流状态')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='预计送达日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '物流追踪',
                'verbose_name_plural': '物流追踪',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('model', models.CharField(max_length=100, verbose_name='产品型号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('stock', models.IntegerField(verbose_name='库存数量')),
                ('description', models.TextField(blank=True, null=True, verbose_name='产品描述')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory', verbose_name='产品分类')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('product_model', models.CharField(max_length=100, verbose_name='产品型号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='小计')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='订单')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
            },
        ),
        migrations.CreateModel(
            name='TrackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='时间')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('status', models.CharField(max_length=100, verbose_name='状态描述')),
                ('details', models.TextField(blank=True, null=True, verbose_name='详细信息')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.logisticstracking', verbose_name='物流追踪')),
            ],
            options={
                'verbose_name': '物流轨迹记录',
                'verbose_name_plural': '物流轨迹记录',
                'ordering': ['-timestamp'],
            },
        ),
    ]
